print('\033[32m=\033[m'*120)
print('{:^100}'.format('BRASILEIRÄO 2021'))
print('\033[32m=\033[m'*120)
times = ('Atlético-MG','Palmeiras','Fortaleza','Flamengo','Bragantino','Corinthians','Atlético-GO','Ceará','Athletico-PR','Internacional','Santos','São Paulo','Juventude','Cuiabá','Bahia','Fluminense','Grêmio','Sport','América-MG','Chapecoense')
print(f'Os 5 primeiros colocados são : {times[0:5]}')
print('='*120)
print(f'Os 4 últimos colocados são : {times[-4:]}')
print('='*120)
print(f'Times em ordem alfabéticas : {sorted(times)}')
print('='*120)
print(f'A Chapecoense está na {times.index("Chapecoense")+1}ª posição.')
